version: '3.8'

services:
  # Backend-Anwendung (HikePlanner)
  backend:
    build: .
    container_name: hikeplanner-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://mongodb:27017/hikeplanner
    depends_on:
      - mongodb

  # Lokale MongoDB für die Entwicklung
  mongodb:
    image: mongo:latest
    container_name: hikeplanner-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: